version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      - "static:/usr/src/app/dist"
  proxy:
    container_name: proxy
    depends_on:
      - app
    image: nginx:latest
    ports:
      - "4000:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./ssl/:/etc/ssl
      - "static:/var/static"
volumes:
  static:
